### ISSUE TITLE
Thoughts about test setups

### ISSUE THREAD

**Issue by joshchernoff** [riverrun/phauxth-example#6]
After reading your user controller test setup I started to look into other ways to do that seeing as I'm building an app with multiple user types. Notably an admin type.  In that case I didn't want to keep adding to the if condition. That lead me down a few paths but in the end I started to re read ExUnit's and found this section. https://hexdocs.pm/ex_unit/ExUnit.Case.html#describe/2

Notice the example:
```
defmodule UserManagementTest do
  use ExUnit.Case, async: true

  describe "when user is logged in and is an admin" do
    setup [:log_user_in, :set_type_to_admin]

    test ...
  end

  describe "when user is logged in and is a manager" do
    setup [:log_user_in, :set_type_to_manager]

    test ...
  end

  defp log_user_in(context) do
    # ...
  end
```

It maybe worth your while to look into how you could dry up your tests by follow that example.

**Comment by riverrun** [comment]
Thanks for the link. I'll look into it.

**Comment by riverrun** [comment]
First of all, many apologies for taking so long over this issue. I have had a pretty rough year, and getting anything done has been a real struggle.

Anyway, this issue was fixed in [this commit on March 20](https://github.com/riverrun/phauxth-example/commit/01ec3decb98e8dec416e89977fdd61f90fa377c0).
